# This file is automatically generated and should not be modified directly. If
# you want to update this file, run `code_generation/generate.py`.

from typing import Final

DATA_VERSION: Final[str] = "25.06"
HOST: Final[str] = "ftp.ebi.ac.uk"
