# This file is automatically generated and should not be modified directly. If
# you want to update this file, run `poetry install`, a post install hook will
# generate this file.

from typing import Final

DATA_VERSION: Final = "22.11"
